name: Publish to npm
permissions: {}
on:
  release:
    types:
      - published
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          cache: npm
      - run: npm ci --ignore-scripts
      - run: npm run lint
      - run: npm test
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      tarball: ${{ steps.pack.outputs.tarball }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          package-manager-cache: false
      - run: npm ci --ignore-scripts
      - run: npm run build
      - run: npm version $TAG_NAME --git-tag-version=false
        env:
          TAG_NAME: ${{ github.ref_name }}
      - id: pack
        run: |-
          TARBALL=$(npm pack)
          echo "tarball=$TARBALL" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: tarball
          path: ${{ steps.pack.outputs.tarball }}
  publish:
    needs:
      - test
      - build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
      TARBALL: ${{ needs.build.outputs.tarball }}
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: tarball
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          package-manager-cache: false
      - run: npm install -g npm@~11.10.0 # Work-around for https://github.com/npm/cli/issues/9151#issuecomment-4131466208
      - run: npm install -g npm@latest
      - run: npm stage publish --provenance --access public --tag next $TARBALL
        if: github.event.release.prerelease
        env:
          TARBALL: ${{ needs.build.outputs.tarball }}
      - run: npm stage publish --provenance --access public $TARBALL
        if: "!github.event.release.prerelease"
        env:
          TARBALL: ${{ needs.build.outputs.tarball }}
